version: '2'

services:

  mqtt:
    restart: always
    image: ${DOCKER_REGISTRY}/onesait-things/edge-mqtt:latest
    container_name: edge.mqtt
    volumes:
      - /home/indra/docker/logs:/mosquitto/log
      - /home/indra/docker/data:/mosquitto/data
    ports:
      - 1883:1883
    networks:
      - edgenet

networks:
  edgenet:
    driver:  bridge
