version: '2'
 
services:
 
  #Inner mqtt broker mandatory by Edge Engine architecture.
  mqtt:
    restart: always
    image: onesaitplatform/edge-mqtt:community
    container_name: edge.mqtt
 
    #Remember define these volumes with edge device local paths.
    volumes:
      - /mosquitto/log
      - /mosquitto/data
    networks:
      - edgenet
 
#Edge Engine Zigbee contanier for working with Zigbee-HA & Zigbee-Lighting devices.
  zigbee:
    restart: always
    image: onesaitplatform/edge:zigbee:community
    container_name: edge.zigbee
    environment:
      CONTAINER_TIMEZONE: Europe/Madrid
      NODE1_ZIGBEE_PORT: /dev/ttyACM0
    #Remember define these volumes with edge device local paths.
    volumes:
      - /mnt/logs
      - /mnt/data
      - /mnt/conf
    # If you need use Zigbee dongle  on /dev/ttyACM0 (as an example)
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mqtt
    links:
      - mqtt
    ports:
     - 4443:4443
    networks:
      - edgenet
 
networks:
  edgenet:
    driver:  bridge
