version: '3'

services:

  mqtt:
    restart: always
    image: ${DOCKER_REGISTRY}/onesait-things/edge-mqtt:latest
    container_name: edge.mqtt
    volumes:
      - /home/indra/docker/logs:/mosquitto/log
      - /home/indra/docker/data:/mosquitto/data
    ports:
      - 1883:1883
    networks:
      - edgenet
  
  nodered:
    restart: always
    image: ${DOCKER_REGISTRY}/onesait-things/edge-nodered:slim
    container_name: edge.nodered
    volumes:
      - /home/indra/docker/data:/home/node
    ports:
      - 1880:1880
    networks:
      - edgenet

networks:
  edgenet:
    driver:  bridge
